import type { Metadata } from 'next';
import './globals.css';
import { SessionProvider } from 'next-auth/react';
import { Toaster } from '@/components/ui/toaster';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
			// className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<SessionProvider>{children}</SessionProvider>
				<Toaster />
			</body>
		</html>
	);
}
